# Includes one of the default files in src/bootstrap/defaults
profile = "dist"
change-id = 125535
[build]
extended = true
tools = [
    "cargo",
    "clippy",
    "rustdoc",
    "rustfmt",
    "rust-analyzer",
    "rust-analyzer-proc-macro-srv",
    "analysis",
    "src",
    "miri",
    "cargo-miri" # for dev/nightly channels
]